name: ESPHome CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Create dummy secrets.yaml
        run: |
          cat <<EOF > firmware/secrets.yaml
          wifi_ssid: 'dummy_ssid'
          wifi_password: 'dummy_password'
          spoolman_ip: '127.0.0.1'
          filaman_ip: '127.0.0.1'
          api_key: 'MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE='
          ota_password: '123'
          github_url: 'github://christophcaina/filament_scale/firmware/example_config.yaml'
          EOF

      - name: Validate ESPHome Config
        run: esphome config firmware/test-all.yaml

  build-release:
    needs: validate # Erst validieren, dann bauen
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write # Wichtig, um das Release zu erstellen
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Create dummy secrets.yaml (Build)
        run: |
          cat <<EOF > firmware/secrets.yaml
          wifi_ssid: 'dummy'
          wifi_password: 'dummy'
          spoolman_ip: '127.0.0.1'
          api_key: 'MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE='
          github_url: 'github://${{ github.repository }}/firmware/example_config.yaml'
          EOF

      - name: Compile Firmware
        run: esphome compile firmware/example_config.yaml

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            firmware/.esphome/build/filament-scale-example/.pioenvs/filament-scale-example/firmware.bin
          name: Release ${{ github.ref_name }}
          body: "Automatischer Build der Firmware Version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}